-- ============================================================================
-- SEEDING — creating your first Admin account
-- ============================================================================
-- Supabase Auth users cannot be created with plain SQL (passwords must go
-- through Supabase's auth API so they're hashed correctly). Create the first
-- admin like this instead:
--
-- 1. Supabase Dashboard -> Authentication -> Users -> "Add user"
--    Create the user with an email + password, "Auto Confirm User" checked.
-- 2. Copy the new user's UUID from the dashboard.
-- 3. Run the statement below with that UUID substituted in, to make it an
--    admin profile (admins have role='admin' and client_id=null):
--
--   insert into public.profiles (id, role, client_id, full_name, email)
--   values (
--     'PASTE-USER-UUID-HERE',
--     'admin',
--     null,
--     'Kynex Admin',
--     'admin@kynexcode.com'
--   );
--
-- After that you can log in at /login with that email/password and use the
-- admin "Clients" page to provision every future client and admin account —
-- the app's "Add client" flow creates the auth user, profile, and clients
-- row together via src/actions/clients.ts using the service role key.
-- ============================================================================

-- ----------------------------------------------------------------------------
-- OPTIONAL: sample data to explore the UI with. Safe to skip in production.
-- Run only after you've created at least one client login through the app
-- (or the dashboard) and captured its client_id + profile id below.
-- ----------------------------------------------------------------------------

-- example (edit the UUIDs to match a real client you've created):
--
-- insert into public.projects (client_id, name, project_type, description, status, start_date, expected_completion_date, live_url)
-- values (
--   'CLIENT-UUID-HERE',
--   'Corporate Website Redesign',
--   'Website Redesign',
--   'Full redesign of the marketing site with a new CMS.',
--   'in_progress',
--   '2026-06-01',
--   '2026-09-15',
--   null
-- );
--
-- insert into public.invoices (client_id, invoice_number, description, amount, status, due_date)
-- values (
--   'CLIENT-UUID-HERE',
--   'INV-2026-0001',
--   'Website Redesign — Milestone 1',
--   1500.00,
--   'pending',
--   '2026-09-01'
-- );
--
-- insert into public.amc (client_id, plan_name, services_included, amount, start_date, renewal_date, status)
-- values (
--   'CLIENT-UUID-HERE',
--   'Standard AMC',
--   array['Uptime monitoring', 'Monthly backups', 'Security patches', '2 hrs/mo content updates'],
--   600.00,
--   '2026-01-01',
--   '2027-01-01',
--   'active'
-- );
